In [3]:
import torch
import torch.distributions as dist

In [19]:
## Lets create a Beroulli distribution
bernoulli = dist.Bernoulli(torch.tensor([.5]))
bernoulli

## Sample the distribution
for _ in range(10):
    print(bernoulli.sample())

tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])


In [23]:
## Calculate some description statistics
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.4950000047683716
Variance: 0.2502252161502838


In [31]:
## Lets create a normal distribution
gaussian = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
for _ in range(10):
    print(gaussian.sample())

tensor([1.1049])
tensor([-0.1747])
tensor([0.8088])
tensor([0.4183])
tensor([-0.3044])
tensor([0.7036])
tensor([-1.9048])
tensor([-0.8897])
tensor([-1.0097])
tensor([-0.7746])


In [ ]:
samples = [gaussian.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

tensor([1.1114])
tensor([1.1891])
tensor([-0.2296])
tensor([-1.3138])
tensor([-2.2008])
tensor([0.0279])
tensor([0.6364])
tensor([1.9385])
tensor([-0.1980])
tensor([1.3477])
Mean: -0.04635487496852875
Variance: 0.9731736183166504


### Key Takeaway
In sampling any probability distribution, you can think of the PyTorch function that generates the distributions as the **data generating distribution**. It is the underlying distribution that is pure and beautiful (think nature), and we only get to observe samples from it. Since we only get to observe samples from it, **the samples never fully match the original distribution**.