## Linear Regression

<img src="my_image.png" width="400">

In [2]:
import torch
import torch.nn as nn

In [28]:
# Create a linear regression model
# Arguments: # of inputs, # of outputs

# Note: Each time you reload the model you will get slightly different results,
#       since the model is initialized with different weights. This is important.

model = nn.Linear(10, 1) 

# Inspect the model 
print(model.weight)
print(model.bias) # Only one bias since only one output

Parameter containing:
tensor([[-0.2726, -0.1904,  0.1215,  0.1054,  0.0621,  0.1855,  0.2700, -0.1199,
         -0.1874, -0.0485]], requires_grad=True)
Parameter containing:
tensor([0.1226], requires_grad=True)


In [29]:
x = torch.ones(10)
model(x)

tensor([0.0483], grad_fn=<ViewBackward0>)

**Notes:** Linear models are ***not*** good for cyclic functions or quadratic functions. They cannot do anything that really is not a nice straight line.